spring.application.name=rag
# ??????? ollama-openai ??
spring.profiles.active=ollama-openai

# ????????? Ollama????? API KEY ??????????
spring.ai.openai.api-key=ollama

# ??????????
spring.ai.vectorstore.milvus.initialize-schema=true

# ???????
management.tracing.enabled=false
management.endpoints.web.exposure.include=prometheus

# ????????????
spring.profiles.group.qianfan=single-document-batching

rag.upload.max-size-bytes=52428800

rag.upload.allowed-ext: pdf,doc,docx,txt,md
